### ISSUE TITLE
remove instructions to use file names for versioning, content, namespacing or branding

### ISSUE THREAD

**Issue by 1O** [eLTER-RI/boilerplate-readme#1]
This part of the README instructs contributers to include versioning and other information in the file names.
```
File naming nomenclature
[...]
Include the project identifier (i.e. eLTER) name at the beginning of the files when possible.
Include a version number at the end of the file name such as v01. Change this version number each time the file is saved.
Include an identifier of what the file is on the file name.
Examples:
eLTER-CODE-data_loading-v01.R
eLTER-DATA-temperature_sensor_data-v01.csv
```
However: versioning is taken care of by Git, namespacing by the library loader, and branding (if that's the intention) through the GitHub account name and README; the users, in turn, aren't exposed to the source file names anyway.

> **recommendation**: omit said instructions *for any source file* as they are bound to get in the way of build and versioning automation.

**Comment by maab** [comment]
I agree, that usually the mechanisms listed here cover the most of the requirements and it is not necessary to encode them into file names as long as they are under version control.

But once we handle files in other contexts (e.g. releases or publishing to platforms like Zenodo) the filename becomes a meaning.

@allantsouza - do you think this could be explained in more detail here?

**Comment by allantsouza** [comment]
Thanks for the question @1O. 
Following naming conventions in files is important to quickly understand what the files are about, as well as which version of the file we are using.
Git can keep record of changes in files (if not added to .gitignore). It is important to record changes in files using versioning. Here, **_I am not referring to all files, but most importantly to input files_**. Maybe this disticntion should be made clear on the readme.

So I propose to modify the instruction to:

- Use descriptive names that reflect the content or purpose of the file.
- Use hyphens (-) to separate different elements of the file name, and underscores (_) to denote spaces within an element.
- Keep file names concise, avoiding unnecessary abbreviations while maintaining sufficient detail.
- Include the project identifier (i.e. eLTER) name at the beginning of the files when possible.
- Include a version number at the end of the file name such as v01 _**for input files**_. Change this version number each time the file is **modified**.
- Include an identifier of what the file is on the file name _**(e.g. CODE, DATA, METADATA, IMAGE...)**_.
- Examples:
  - `eLTER-CODE-data_loading-v01.R`
  - `eLTER-DATA-temperature_sensor_data-v01.csv`

**Comment by Kulivox** [comment]
Hi, @allantsouza; I have to agree with the others in this thread. I see no reason to use the naming convention (elter prefix, version suffix) you proposed **outside of data files and release artefacts**. Furthermore, I do not understand the need for the `ELTER-CODE` prefix for code files. In my opinion, they only add unnecessary visual noise, as it is obvious that the files are relevant to eLTER project, as I am in an eLTER repository, and the file extension (or a simple visual inspection of the contents) tells me they are code files.

I have also never encountered such a peculiar naming policy. Therefore, I think it would only make introducing new developers to projects with such a convention harder.

**Comment by allantsouza** [comment]
Hello @Kulivox please take a look at page 8 of [this document](https://zenodo.org/records/1914401). If you want it, I can provide an extensive list of examples that say the exact same thing about naming conventions.

It might seem peculiar to you because proper data management is rarely implemented in several projects. You have to think that files should be understandable by anyone without making visual inspection of the contents like you've suggested..

I propose now to apply the file naming convention to all files in **assets** folder. I can amend the instructions to state this clearly, but I do not agre that this is not necessary, nor that it adds noise.

Proposed new format for instructions:

- Use descriptive names that reflect the content or purpose of the file in the **files stored in assets folder**.
- Use hyphens (-) to separate different elements of the file name, and underscores (_) to denote spaces within an element.
- Keep file names concise, avoiding unnecessary abbreviations while maintaining sufficient detail.
- Include the project identifier (i.e. eLTER) name at the beginning of the files when possible.
- Include a version number at the end of the file name such as v01 for input files. Change this version number each time the file is modified.
- Include an identifier of what the file is on the file name (e.g. CODE, DATA, METADATA, IMAGE...).
   - Examples:
     - `eLTER-IMAGE-PPP_logo-v01.jpeg`
     - `eLTER-DATA-temperature_sensor_data-v01.csv`
